### ISSUE TITLE
Hide everything does not hide everything

### ISSUE THREAD

**Issue by 1unar-Eclipse** [kinsi55/CS_BeatSaber_FocusMod#1]
-Hide only in VR on: Nothing hides in VR, period. Things *do* hide on the *desktop*, however. (Image on desktop - take my word for it in VR.)

-Hide only in VR off: Same thing as Image, but in VR too.

Image: ![image](https://user-images.githubusercontent.com/74077800/104242829-b57c0f00-542d-11eb-841b-e8cabe347496.png)

I'd like a toggle, as well. There's no clear way to turn this off.

**Comment by kinsi55** [comment]
I literally just released an update that addresses the Combo number (0 in your image) not hiding - The song Progress not hiding is intentional (Eventho it will only not hide in certain configurations), but that obviously does not address your other problems, so to look into that...

Are you on the Steam version?

Do you use Camera+, Smooth camera or neither?

Can you share me your Counters+ Config? Its in UserData and called CountersPlus.json, you can rename it to .txt or zip it so you can attach it in your comment.

To turn it off simply change the first setting to 0, like the hint annotates. I should probably move the (0 = Off) part to the setting name instead of the hint

**Comment by 1unar-Eclipse** [comment]
Yes, I am on Steam.

I use the built-in Smooth Camera. Camera+ hasn't been installed in a long time.

I do not have Counters+, but I have used it before. Here's my config:
[CountersPlus.txt](https://github.com/kinsi55/CS_BeatSaber_FocusMod/files/5798605/CountersPlus.txt)

And didn't read that hint; that's on me.

**Comment by kinsi55** [comment]
Ok I think I figured things out, can you try this and see if it fixes all your issues?
[FocusMod.zip](https://github.com/kinsi55/CS_BeatSaber_FocusMod/files/5798766/FocusMod.zip)

**Comment by 1unar-Eclipse** [comment]
I'll get back to you when I play again.

**Comment by CypherNL** [comment]
I also have this issue as well. I do use Camera+ but not Counters+.
Using the version attached in the issue, it does hide the score for me now. I haven't tried to enable hide only in VR or use the non-advanced HUD yet as i'm just done with my Beat Saber session. But it does work now using hide everything, advanced HUD and with Camera+.

**Comment by kinsi55** [comment]
Thanks for the feedback, as far as my testing is concerned this seems to fix all issues that he mentioned so I guess I will go ahead and publish the update..
